import React from 'react'


const CardModePage = () => {
    return (
        <div>
            CARDS
            <br/>
            CARDS
            <br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDS<br/>
            CARDSv
        </div>
    )
}

export default CardModePage