export const PROFILE_ROUTE = (id) => id ? `/profile/${id}` : '/profile:id'
export const MAIN_PAGE_ROUTE = '/'
export const CHOSE_MOD_ROUTE = '/mode'
export const CARDS_MODE_ROUTE = '/cards'
export const AUTH_ROUTE = '/authentication'