export const PROFILE_ROUTE = (id) => id ? `/profile/${id}` : '/profile:id'
export const MAIN_PAGE_ROUTE = '/'
export const CHOSE_MOD_ROUTE = '/mode'
export const CARDS_MODE_ROUTE = '/cards'
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'